# Generated by Django 5.1.3 on 2024-12-08 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_slots', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('contact', models.CharField(max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_smart', models.BooleanField(default=False)),
                ('two_wheeler_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('four_wheeler_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='parking_images/')),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='is_parking_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_num', models.PositiveIntegerField()),
                ('url', models.URLField(max_length=400)),
                ('car_spots', models.JSONField()),
                ('bike_spots', models.JSONField()),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.parking')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=20)),
                ('organization', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='parking',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.parkingowner'),
        ),
        migrations.DeleteModel(
            name='Cameras',
        ),
        migrations.DeleteModel(
            name='Parkings',
        ),
    ]
