# Generated by Django 5.1.3 on 2024-12-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_parking_users_is_parking_owner_camera_parkingowner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='is_logistic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parking',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='total_slots',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
