# Generated by Django 5.1.3 on 2024-12-11 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_parking_is_logistic_alter_parking_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='bike_spots',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='car_spots',
        ),
        migrations.AddField(
            model_name='camera',
            name='spots',
            field=models.JSONField(null=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_num', models.CharField(max_length=20)),
                ('checkin_time', models.DateTimeField()),
                ('checkout_time', models.DateTimeField()),
                ('is_checked_out', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_paid', models.BooleanField(default=False)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.parking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
