# Generated by Django 5.1.3 on 2024-12-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_camera_bike_spots_remove_camera_car_spots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slot_timing',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
