# Generated by Django 5.1.3 on 2024-12-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_booking_slot_timing_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='contact',
            field=models.CharField(default='121', max_length=20),
        ),
    ]
