# Generated by Django 5.1.3 on 2024-12-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_users_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin_time',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_time',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='slot_timing',
            field=models.CharField(null=True),
        ),
    ]
